# Generated by Django 3.1.5 on 2021-01-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_number',
        ),
    ]
