# Generated by Django 3.1.5 on 2021-01-27 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
