# Generated by Django 3.1.5 on 2021-01-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order processing', 'Order processing'), ('Order on the way', 'Order on the way'), ('Order Not Yet Recieved', 'Order Not Yet Recieved')], default='Order Not Yet Recieved', max_length=100),
        ),
    ]
