# Generated by Django 3.1.5 on 2021-01-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
