# Generated by Django 3.1.5 on 2021-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210128_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='full_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
