# Generated by Django 3.1.5 on 2021-02-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_shippingaddress_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='Payment_method',
            field=models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery'), ('Card Payment', 'Card Payment')], default='Pay On Delivery', max_length=100),
        ),
    ]
