# Generated by Django 3.1.5 on 2021-02-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_shippingaddress_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='Payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
